### ISSUE TITLE
undefined local variable or method `recaptcha_tags' in v0.6.0

### ISSUE THREAD

**Issue by fmh** [ambethia/recaptcha#143]
I have this error after upgrade from v0.3 to v0.6 
````
undefined local variable or method `recaptcha_tags' for #<Class:0x007fd132fd5f60>:0x007fd1369a9160>
````
Rails : 4.2.3
Ruby 2.2.1

**Comment by grosser** [comment]
more backtrace would be great :)

it's defined in the Recaptcha::ClientHelper so I'd guess that is not included ... which might mean the railtie is not loaded ... 

are you using `gem "recaptcha", require: "recaptcha/rails"` ?

**Comment by fmh** [comment]
No, i use gem "recaptcha"
`````
NameError - undefined local variable or method `recaptcha_tags' for #<#<Class:0x007fd132fd5f60>:0x007fd134e12f50>:
  app/views/devise/registrations/new.html.haml:32:in `block (2 levels) in _app_views_devise_registrations_new_html_haml__2997623792405197220_70268270448060'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
  haml (4.0.7) lib/haml/helpers.rb:278:in `with_tabs'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.3) lib/action_view/helpers/form_helper.rb:444:in `form_for'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
  app/views/devise/registrations/new.html.haml:5:in `block in _app_views_devise_registrations_new_html_haml__2997623792405197220_70268270448060'
  haml (4.0.7) lib/haml/helpers.rb:368:in `block in capture_haml'
  haml (4.0.7) lib/haml/helpers.rb:608:in `with_haml_buffer'
  haml (4.0.7) lib/haml/helpers.rb:364:in `capture_haml'
  haml (4.0.7) lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
  app/views/devise/registrations/new.html.haml:1:in `_app_views_devise_registrations_new_html_haml__2997623792405197220_70268270448060'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/fmh/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:30:in `cleanup_view_runtime'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.0.1) lib/wicked_pdf/pdf_helper.rb:23:in `render_with_wicked_pdf'
  remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:236:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.1.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.1.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.1.0) lib/action_controller/respond_with.rb:203:in `respond_with'
  devise (3.5.2) app/controllers/devise/registrations_controller.rb:10:in `new'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.3) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.3) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<top (required)>'
  -e:1:in `<main>'
````

**Comment by grosser** [comment]
yeah, that no longer sets up all helpers / rails integration, can you switch to `gem "recaptcha", require: "recaptcha/rails"` ?

**Comment by fmh** [comment]
now, it work !
thx :)

**Comment by grosser** [comment]
Comment is there since 2011 77a7751b ... so it looks like it worked by accident before when added for rails 3 with d0c544e8 or nobody documented it ... I'd opt to keep it clean / not auto change rails if this is the only downside

**Comment by fmh** [comment]
super, thx

**Comment by Tosh39** [comment]
Awesome!
It worked.
