### ISSUE TITLE
Error after upgrade to 0.6 (from 0.4)

### ISSUE THREAD

**Issue by dannyphung** [ambethia/recaptcha#145]
I got Name Error: ``` undefined local variable or method `recaptcha_tags' for #<#<Class:``` after upgrade to 0.6, I tried 0.5 but got same error. I'm using rails 4.2.5.

**Comment by grosser** [comment]
Sorry for the trouble ... I think this is the same as https://github.com/ambethia/recaptcha/issues/143

`gem "recaptcha", require: "recaptcha/rails"`
